Feature/workflow reuse (#24)
* Fail tests

* Enable failing test

* Enable tests on dispatch

* Lock dotnet version to 8.0.6 for now

* Continue on error

* Fix dotnet

* Check for failed tests

* Make release depend on tests

* Make tests.yml reusable

* Grant permissions to the workflow

* Finaliza pr

* format

* Fix echo

* Edit messages

* Set persist-credentials to false

* Add filters

* Make actual release depend on tests, not the check-release job

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -3,7 +3,13 @@ on:
   push:
     branches:
       - main
+    paths-ignore:
+      - '**.md'
   pull_request:
+    paths-ignore:
+      - '**.md'
+  workflow_dispatch:
+  workflow_call:
 permissions: { }
 env:
   DOTNET_CLI_TELEMETRY_OPTOUT: true
@@ -11,6 +17,7 @@ env:
 jobs:
   test:
     name: Tests
+    continue-on-error: true
     strategy:
       matrix:
         os:
@@ -18,7 +25,7 @@ jobs:
           - windows-latest
           - macos-latest
         dotnet:
-          - 8.0.x
+          - 8.0.302
     runs-on: ${{ matrix.os }}
     permissions:
       contents: read
@@ -50,3 +57,26 @@ jobs:
           name: dotnet-${{ steps.dotnet-setup.outputs.dotnet-version }}-tests-on-${{ matrix.os }}
           path: TestResults
         if: ${{ always() }}
+  test-check:
+    name: Fail if tests failed
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    if: ${{ always() }}
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
+        with:
+          egress-policy: audit
+          disable-telemetry: true
+      - name: Check for failed tests
+        run: |
+          echo "::debug::Checking for failed tests..."
+          echo "::debug::Job result: ${{ needs.test.result }}"
+          for job in "${{ needs.test.result }}"; do
+            if [[ "$job" == "failure" ]]; then
+              echo "::error Some matrix jobs failed."
+              exit 1
+            fi
+          done
+          echo "All tests succeeded."
